//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterskiScoringSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MemberList_Width {
            get {
                return ((int)(this["MemberList_Width"]));
            }
            set {
                this["MemberList_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MemberList_Height {
            get {
                return ((int)(this["MemberList_Height"]));
            }
            set {
                this["MemberList_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourList_Width {
            get {
                return ((int)(this["TourList_Width"]));
            }
            set {
                this["TourList_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourList_Height {
            get {
                return ((int)(this["TourList_Height"]));
            }
            set {
                this["TourList_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TourList_Location {
            get {
                return ((global::System.Drawing.Point)(this["TourList_Location"]));
            }
            set {
                this["TourList_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MemberList_Location {
            get {
                return ((global::System.Drawing.Point)(this["MemberList_Location"]));
            }
            set {
                this["MemberList_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mdi_Width {
            get {
                return ((int)(this["Mdi_Width"]));
            }
            set {
                this["Mdi_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mdi_Height {
            get {
                return ((int)(this["Mdi_Height"]));
            }
            set {
                this["Mdi_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Mdi_Location {
            get {
                return ((global::System.Drawing.Point)(this["Mdi_Location"]));
            }
            set {
                this["Mdi_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppSanctionNum {
            get {
                return ((string)(this["AppSanctionNum"]));
            }
            set {
                this["AppSanctionNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportDirectory {
            get {
                return ((string)(this["ExportDirectory"]));
            }
            set {
                this["ExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ImportMatch_Location {
            get {
                return ((global::System.Drawing.Point)(this["ImportMatch_Location"]));
            }
            set {
                this["ImportMatch_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NopsCalcForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["NopsCalcForm_Location"]));
            }
            set {
                this["NopsCalcForm_Location"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WSTIMS For Windows")]
        public string AppTitle {
            get {
                return ((string)(this["AppTitle"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NopsMaint_Location {
            get {
                return ((global::System.Drawing.Point)(this["NopsMaint_Location"]));
            }
            set {
                this["NopsMaint_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NopsMaint_Height {
            get {
                return ((int)(this["NopsMaint_Height"]));
            }
            set {
                this["NopsMaint_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NopsMaint_Width {
            get {
                return ((int)(this["NopsMaint_Width"]));
            }
            set {
                this["NopsMaint_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ListMaint_Location {
            get {
                return ((global::System.Drawing.Point)(this["ListMaint_Location"]));
            }
            set {
                this["ListMaint_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ListMaint_Height {
            get {
                return ((int)(this["ListMaint_Height"]));
            }
            set {
                this["ListMaint_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ListMaint_Width {
            get {
                return ((int)(this["ListMaint_Width"]));
            }
            set {
                this["ListMaint_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SkierRanking_Location {
            get {
                return ((global::System.Drawing.Point)(this["SkierRanking_Location"]));
            }
            set {
                this["SkierRanking_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SkierRanking_Height {
            get {
                return ((int)(this["SkierRanking_Height"]));
            }
            set {
                this["SkierRanking_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SkierRanking_Width {
            get {
                return ((int)(this["SkierRanking_Width"]));
            }
            set {
                this["SkierRanking_Width"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WaterskiScoringSystem.exe")]
        public string AppExeName {
            get {
                return ((string)(this["AppExeName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\waterski.sdf;Password=waterski;Persist Security Info=" +
            "True")]
        public string waterskiConnectionLocalString {
            get {
                return ((string)(this["waterskiConnectionLocalString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourRegList_Width {
            get {
                return ((int)(this["TourRegList_Width"]));
            }
            set {
                this["TourRegList_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourRegList_Height {
            get {
                return ((int)(this["TourRegList_Height"]));
            }
            set {
                this["TourRegList_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TourRegList_Location {
            get {
                return ((global::System.Drawing.Point)(this["TourRegList_Location"]));
            }
            set {
                this["TourRegList_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Mdi_Title {
            get {
                return ((string)(this["Mdi_Title"]));
            }
            set {
                this["Mdi_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunningOrder_Height {
            get {
                return ((int)(this["RunningOrder_Height"]));
            }
            set {
                this["RunningOrder_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunningOrder_Width {
            get {
                return ((int)(this["RunningOrder_Width"]));
            }
            set {
                this["RunningOrder_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RunningOrder_Location {
            get {
                return ((global::System.Drawing.Point)(this["RunningOrder_Location"]));
            }
            set {
                this["RunningOrder_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomEntry_Height {
            get {
                return ((int)(this["SlalomEntry_Height"]));
            }
            set {
                this["SlalomEntry_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomEntry_Width {
            get {
                return ((int)(this["SlalomEntry_Width"]));
            }
            set {
                this["SlalomEntry_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlalomEntry_Location {
            get {
                return ((global::System.Drawing.Point)(this["SlalomEntry_Location"]));
            }
            set {
                this["SlalomEntry_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickEntry_Height {
            get {
                return ((int)(this["TrickEntry_Height"]));
            }
            set {
                this["TrickEntry_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickEntry_Width {
            get {
                return ((int)(this["TrickEntry_Width"]));
            }
            set {
                this["TrickEntry_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TrickEntry_Location {
            get {
                return ((global::System.Drawing.Point)(this["TrickEntry_Location"]));
            }
            set {
                this["TrickEntry_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpEntry_Height {
            get {
                return ((int)(this["JumpEntry_Height"]));
            }
            set {
                this["JumpEntry_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpEntry_Width {
            get {
                return ((int)(this["JumpEntry_Width"]));
            }
            set {
                this["JumpEntry_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point JumpEntry_Location {
            get {
                return ((global::System.Drawing.Point)(this["JumpEntry_Location"]));
            }
            set {
                this["JumpEntry_Location"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\waterski.sdf;Password=waterski;Persist Security Info=" +
            "True")]
        public string waterskiConnectionString {
            get {
                return ((string)(this["waterskiConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomScoreSummary_Width {
            get {
                return ((int)(this["SlalomScoreSummary_Width"]));
            }
            set {
                this["SlalomScoreSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomScoreSummary_Height {
            get {
                return ((int)(this["SlalomScoreSummary_Height"]));
            }
            set {
                this["SlalomScoreSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlalomScoreSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["SlalomScoreSummary_Location"]));
            }
            set {
                this["SlalomScoreSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpCalc_Height {
            get {
                return ((int)(this["JumpCalc_Height"]));
            }
            set {
                this["JumpCalc_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpCalc_Width {
            get {
                return ((int)(this["JumpCalc_Width"]));
            }
            set {
                this["JumpCalc_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point JumpCalc_Location {
            get {
                return ((global::System.Drawing.Point)(this["JumpCalc_Location"]));
            }
            set {
                this["JumpCalc_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickCalc_Width {
            get {
                return ((int)(this["TrickCalc_Width"]));
            }
            set {
                this["TrickCalc_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TrickCalc_Location {
            get {
                return ((global::System.Drawing.Point)(this["TrickCalc_Location"]));
            }
            set {
                this["TrickCalc_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickCalc_Height {
            get {
                return ((int)(this["TrickCalc_Height"]));
            }
            set {
                this["TrickCalc_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickScoreSummary_Width {
            get {
                return ((int)(this["TrickScoreSummary_Width"]));
            }
            set {
                this["TrickScoreSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickScoreSummary_Height {
            get {
                return ((int)(this["TrickScoreSummary_Height"]));
            }
            set {
                this["TrickScoreSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpScoreSummary_Width {
            get {
                return ((int)(this["JumpScoreSummary_Width"]));
            }
            set {
                this["JumpScoreSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpScoreSummary_Height {
            get {
                return ((int)(this["JumpScoreSummary_Height"]));
            }
            set {
                this["JumpScoreSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point JumpScoreSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["JumpScoreSummary_Location"]));
            }
            set {
                this["JumpScoreSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OfficialWorkRecord_Width {
            get {
                return ((int)(this["OfficialWorkRecord_Width"]));
            }
            set {
                this["OfficialWorkRecord_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OfficialWorkRecord_Height {
            get {
                return ((int)(this["OfficialWorkRecord_Height"]));
            }
            set {
                this["OfficialWorkRecord_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OfficialWorkRecord_Location {
            get {
                return ((global::System.Drawing.Point)(this["OfficialWorkRecord_Location"]));
            }
            set {
                this["OfficialWorkRecord_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OfficialWorkRecord_Sort {
            get {
                return ((string)(this["OfficialWorkRecord_Sort"]));
            }
            set {
                this["OfficialWorkRecord_Sort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OfficialWorkReport_Width {
            get {
                return ((int)(this["OfficialWorkReport_Width"]));
            }
            set {
                this["OfficialWorkReport_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OfficialWorkReport_Height {
            get {
                return ((int)(this["OfficialWorkReport_Height"]));
            }
            set {
                this["OfficialWorkReport_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OfficialWorkReport_Location {
            get {
                return ((global::System.Drawing.Point)(this["OfficialWorkReport_Location"]));
            }
            set {
                this["OfficialWorkReport_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OfficialWorkReport_Sort {
            get {
                return ((string)(this["OfficialWorkReport_Sort"]));
            }
            set {
                this["OfficialWorkReport_Sort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0.0.12")]
        public string AppVersion {
            get {
                return ((string)(this["AppVersion"]));
            }
            set {
                this["AppVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MasterSummary_Height {
            get {
                return ((int)(this["MasterSummary_Height"]));
            }
            set {
                this["MasterSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MasterSummary_Width {
            get {
                return ((int)(this["MasterSummary_Width"]));
            }
            set {
                this["MasterSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MasterSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["MasterSummary_Location"]));
            }
            set {
                this["MasterSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppRegistryName {
            get {
                return ((string)(this["AppRegistryName"]));
            }
            set {
                this["AppRegistryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("waterskiConnectionLocalString")]
        public string AppConnectName {
            get {
                return ((string)(this["AppConnectName"]));
            }
            set {
                this["AppConnectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickList_Height {
            get {
                return ((int)(this["TrickList_Height"]));
            }
            set {
                this["TrickList_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickList_Width {
            get {
                return ((int)(this["TrickList_Width"]));
            }
            set {
                this["TrickList_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TrickList_Location {
            get {
                return ((global::System.Drawing.Point)(this["TrickList_Location"]));
            }
            set {
                this["TrickList_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TrickList_Sort {
            get {
                return ((string)(this["TrickList_Sort"]));
            }
            set {
                this["TrickList_Sort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpMeterSetup_Height {
            get {
                return ((int)(this["JumpMeterSetup_Height"]));
            }
            set {
                this["JumpMeterSetup_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpMeterSetup_Width {
            get {
                return ((int)(this["JumpMeterSetup_Width"]));
            }
            set {
                this["JumpMeterSetup_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point JumpMeterSetup_Location {
            get {
                return ((global::System.Drawing.Point)(this["JumpMeterSetup_Location"]));
            }
            set {
                this["JumpMeterSetup_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChiefJudgeReport_Height {
            get {
                return ((int)(this["ChiefJudgeReport_Height"]));
            }
            set {
                this["ChiefJudgeReport_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChiefJudgeReport_Width {
            get {
                return ((int)(this["ChiefJudgeReport_Width"]));
            }
            set {
                this["ChiefJudgeReport_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ChiefJudgeReport_Location {
            get {
                return ((global::System.Drawing.Point)(this["ChiefJudgeReport_Location"]));
            }
            set {
                this["ChiefJudgeReport_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourChiefOfficial_Width {
            get {
                return ((int)(this["TourChiefOfficial_Width"]));
            }
            set {
                this["TourChiefOfficial_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourChiefOfficial_Height {
            get {
                return ((int)(this["TourChiefOfficial_Height"]));
            }
            set {
                this["TourChiefOfficial_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TourChiefOfficial_Location {
            get {
                return ((global::System.Drawing.Point)(this["TourChiefOfficial_Location"]));
            }
            set {
                this["TourChiefOfficial_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourEventTech_Width {
            get {
                return ((int)(this["TourEventTech_Width"]));
            }
            set {
                this["TourEventTech_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourEventTech_Height {
            get {
                return ((int)(this["TourEventTech_Height"]));
            }
            set {
                this["TourEventTech_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TourEventTech_Location {
            get {
                return ((global::System.Drawing.Point)(this["TourEventTech_Location"]));
            }
            set {
                this["TourEventTech_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourRuleExcept_Width {
            get {
                return ((int)(this["TourRuleExcept_Width"]));
            }
            set {
                this["TourRuleExcept_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourRuleExcept_Height {
            get {
                return ((int)(this["TourRuleExcept_Height"]));
            }
            set {
                this["TourRuleExcept_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TourRuleExcept_Location {
            get {
                return ((global::System.Drawing.Point)(this["TourRuleExcept_Location"]));
            }
            set {
                this["TourRuleExcept_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoatUse_Height {
            get {
                return ((int)(this["BoatUse_Height"]));
            }
            set {
                this["BoatUse_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoatUse_Width {
            get {
                return ((int)(this["BoatUse_Width"]));
            }
            set {
                this["BoatUse_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BoatUse_Location {
            get {
                return ((global::System.Drawing.Point)(this["BoatUse_Location"]));
            }
            set {
                this["BoatUse_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoatUseReport_Width {
            get {
                return ((int)(this["BoatUseReport_Width"]));
            }
            set {
                this["BoatUseReport_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoatUseReport_Height {
            get {
                return ((int)(this["BoatUseReport_Height"]));
            }
            set {
                this["BoatUseReport_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BoatUseReport_Location {
            get {
                return ((global::System.Drawing.Point)(this["BoatUseReport_Location"]));
            }
            set {
                this["BoatUseReport_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SafetyCheckList_Width {
            get {
                return ((int)(this["SafetyCheckList_Width"]));
            }
            set {
                this["SafetyCheckList_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SafetyCheckList_Height {
            get {
                return ((int)(this["SafetyCheckList_Height"]));
            }
            set {
                this["SafetyCheckList_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SafetyCheckList_Location {
            get {
                return ((global::System.Drawing.Point)(this["SafetyCheckList_Location"]));
            }
            set {
                this["SafetyCheckList_Location"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=C:\\apps\\WaterskiScoring\\Data\\WaterskiDev.sdf;Password=waterski;Persis" +
            "t Security Info=True")]
        public string waterskiConnectionString1 {
            get {
                return ((string)(this["waterskiConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomTeamSummary_Width {
            get {
                return ((int)(this["SlalomTeamSummary_Width"]));
            }
            set {
                this["SlalomTeamSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomTeamSummary_Height {
            get {
                return ((int)(this["SlalomTeamSummary_Height"]));
            }
            set {
                this["SlalomTeamSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlalomTeamSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["SlalomTeamSummary_Location"]));
            }
            set {
                this["SlalomTeamSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpTeamSummary_Width {
            get {
                return ((int)(this["JumpTeamSummary_Width"]));
            }
            set {
                this["JumpTeamSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpTeamSummary_Height {
            get {
                return ((int)(this["JumpTeamSummary_Height"]));
            }
            set {
                this["JumpTeamSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point JumpTeamSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["JumpTeamSummary_Location"]));
            }
            set {
                this["JumpTeamSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickTeamSummary_Width {
            get {
                return ((int)(this["TrickTeamSummary_Width"]));
            }
            set {
                this["TrickTeamSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickTeamSummary_Height {
            get {
                return ((int)(this["TrickTeamSummary_Height"]));
            }
            set {
                this["TrickTeamSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TrickTeamSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["TrickTeamSummary_Location"]));
            }
            set {
                this["TrickTeamSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverallTeamSummary_Width {
            get {
                return ((int)(this["OverallTeamSummary_Width"]));
            }
            set {
                this["OverallTeamSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverallTeamSummary_Height {
            get {
                return ((int)(this["OverallTeamSummary_Height"]));
            }
            set {
                this["OverallTeamSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OverallTeamSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["OverallTeamSummary_Location"]));
            }
            set {
                this["OverallTeamSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TeamSummary_Width {
            get {
                return ((int)(this["TeamSummary_Width"]));
            }
            set {
                this["TeamSummary_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TeamSummary_Height {
            get {
                return ((int)(this["TeamSummary_Height"]));
            }
            set {
                this["TeamSummary_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TeamSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["TeamSummary_Location"]));
            }
            set {
                this["TeamSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\waterski.sdf;Password=waterski;Persist Security Info=" +
            "True")]
        public string waterskiConnectionStringApp {
            get {
                return ((string)(this["waterskiConnectionStringApp"]));
            }
            set {
                this["waterskiConnectionStringApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MasterSummaryOverallUS_Width {
            get {
                return ((int)(this["MasterSummaryOverallUS_Width"]));
            }
            set {
                this["MasterSummaryOverallUS_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MasterSummaryOverallUS_Height {
            get {
                return ((int)(this["MasterSummaryOverallUS_Height"]));
            }
            set {
                this["MasterSummaryOverallUS_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MasterSummaryOverallUS_Location {
            get {
                return ((global::System.Drawing.Point)(this["MasterSummaryOverallUS_Location"]));
            }
            set {
                this["MasterSummaryOverallUS_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OfficialWorkAsgmt_Width {
            get {
                return ((int)(this["OfficialWorkAsgmt_Width"]));
            }
            set {
                this["OfficialWorkAsgmt_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OfficialWorkAsgmt_Height {
            get {
                return ((int)(this["OfficialWorkAsgmt_Height"]));
            }
            set {
                this["OfficialWorkAsgmt_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OfficialWorkAsgmt_Location {
            get {
                return ((global::System.Drawing.Point)(this["OfficialWorkAsgmt_Location"]));
            }
            set {
                this["OfficialWorkAsgmt_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OfficialWorkAsgmt_Sort {
            get {
                return ((string)(this["OfficialWorkAsgmt_Sort"]));
            }
            set {
                this["OfficialWorkAsgmt_Sort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MasterSummaryV2_Width {
            get {
                return ((int)(this["MasterSummaryV2_Width"]));
            }
            set {
                this["MasterSummaryV2_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MasterSummaryV2_Height {
            get {
                return ((int)(this["MasterSummaryV2_Height"]));
            }
            set {
                this["MasterSummaryV2_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MasterSummaryV2_Location {
            get {
                return ((global::System.Drawing.Point)(this["MasterSummaryV2_Location"]));
            }
            set {
                this["MasterSummaryV2_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditMember_Width {
            get {
                return ((int)(this["EditMember_Width"]));
            }
            set {
                this["EditMember_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditMember_Height {
            get {
                return ((int)(this["EditMember_Height"]));
            }
            set {
                this["EditMember_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditMember_Location {
            get {
                return ((global::System.Drawing.Point)(this["EditMember_Location"]));
            }
            set {
                this["EditMember_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RerideReason_Location {
            get {
                return ((global::System.Drawing.Point)(this["RerideReason_Location"]));
            }
            set {
                this["RerideReason_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditRegMember_Height {
            get {
                return ((int)(this["EditRegMember_Height"]));
            }
            set {
                this["EditRegMember_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditRegMember_Width {
            get {
                return ((int)(this["EditRegMember_Width"]));
            }
            set {
                this["EditRegMember_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditRegMember_Location {
            get {
                return ((global::System.Drawing.Point)(this["EditRegMember_Location"]));
            }
            set {
                this["EditRegMember_Location"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0.0.12 8/25/2016")]
        public string BuildVersion {
            get {
                return ((string)(this["BuildVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SkierDoneReason_Location {
            get {
                return ((global::System.Drawing.Point)(this["SkierDoneReason_Location"]));
            }
            set {
                this["SkierDoneReason_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TeamSetup_Width {
            get {
                return ((int)(this["TeamSetup_Width"]));
            }
            set {
                this["TeamSetup_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TeamSetup_Height {
            get {
                return ((int)(this["TeamSetup_Height"]));
            }
            set {
                this["TeamSetup_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TeamSetup_Location {
            get {
                return ((global::System.Drawing.Point)(this["TeamSetup_Location"]));
            }
            set {
                this["TeamSetup_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlalomOptup_Location {
            get {
                return ((global::System.Drawing.Point)(this["SlalomOptup_Location"]));
            }
            set {
                this["SlalomOptup_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DivOrder_Width {
            get {
                return ((int)(this["DivOrder_Width"]));
            }
            set {
                this["DivOrder_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DivOrder_Location {
            get {
                return ((global::System.Drawing.Point)(this["DivOrder_Location"]));
            }
            set {
                this["DivOrder_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DivOrder_Height {
            get {
                return ((int)(this["DivOrder_Height"]));
            }
            set {
                this["DivOrder_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomScorebook_Width {
            get {
                return ((int)(this["SlalomScorebook_Width"]));
            }
            set {
                this["SlalomScorebook_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlalomScorebook_Height {
            get {
                return ((int)(this["SlalomScorebook_Height"]));
            }
            set {
                this["SlalomScorebook_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlalomScorebook_Location {
            get {
                return ((global::System.Drawing.Point)(this["SlalomScorebook_Location"]));
            }
            set {
                this["SlalomScorebook_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickScorebook_Width {
            get {
                return ((int)(this["TrickScorebook_Width"]));
            }
            set {
                this["TrickScorebook_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrickScorebook_Height {
            get {
                return ((int)(this["TrickScorebook_Height"]));
            }
            set {
                this["TrickScorebook_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TrickScorebook_Location {
            get {
                return ((global::System.Drawing.Point)(this["TrickScorebook_Location"]));
            }
            set {
                this["TrickScorebook_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpScorebook_Width {
            get {
                return ((int)(this["JumpScorebook_Width"]));
            }
            set {
                this["JumpScorebook_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JumpScorebook_Height {
            get {
                return ((int)(this["JumpScorebook_Height"]));
            }
            set {
                this["JumpScorebook_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point JumpScorebook_Location {
            get {
                return ((global::System.Drawing.Point)(this["JumpScorebook_Location"]));
            }
            set {
                this["JumpScorebook_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JumpScorebookDataType {
            get {
                return ((string)(this["JumpScorebookDataType"]));
            }
            set {
                this["JumpScorebookDataType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JumpScorebookPointsMethod {
            get {
                return ((string)(this["JumpScorebookPointsMethod"]));
            }
            set {
                this["JumpScorebookPointsMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JumpScorebookPlcmtOrg {
            get {
                return ((string)(this["JumpScorebookPlcmtOrg"]));
            }
            set {
                this["JumpScorebookPlcmtOrg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EventRunStats_Width {
            get {
                return ((int)(this["EventRunStats_Width"]));
            }
            set {
                this["EventRunStats_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EventRunStats_Height {
            get {
                return ((int)(this["EventRunStats_Height"]));
            }
            set {
                this["EventRunStats_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EventRunStats_Location {
            get {
                return ((global::System.Drawing.Point)(this["EventRunStats_Location"]));
            }
            set {
                this["EventRunStats_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunningOrderRound_Width {
            get {
                return ((int)(this["RunningOrderRound_Width"]));
            }
            set {
                this["RunningOrderRound_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunningOrderRound_Height {
            get {
                return ((int)(this["RunningOrderRound_Height"]));
            }
            set {
                this["RunningOrderRound_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RunningOrderRound_Location {
            get {
                return ((global::System.Drawing.Point)(this["RunningOrderRound_Location"]));
            }
            set {
                this["RunningOrderRound_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("score")]
        public string RunOrderElimPlcmtMethod {
            get {
                return ((string)(this["RunOrderElimPlcmtMethod"]));
            }
            set {
                this["RunOrderElimPlcmtMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nops")]
        public string RunOrderElimPointsMethod {
            get {
                return ((string)(this["RunOrderElimPointsMethod"]));
            }
            set {
                this["RunOrderElimPointsMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div")]
        public string RunOrderElimPlcmtOrg {
            get {
                return ((string)(this["RunOrderElimPlcmtOrg"]));
            }
            set {
                this["RunOrderElimPlcmtOrg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunOrderElim_Width {
            get {
                return ((int)(this["RunOrderElim_Width"]));
            }
            set {
                this["RunOrderElim_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunOrderElim_Height {
            get {
                return ((int)(this["RunOrderElim_Height"]));
            }
            set {
                this["RunOrderElim_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RunOrderElim_Location {
            get {
                return ((global::System.Drawing.Point)(this["RunOrderElim_Location"]));
            }
            set {
                this["RunOrderElim_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunOrderCopy_Width {
            get {
                return ((int)(this["RunOrderCopy_Width"]));
            }
            set {
                this["RunOrderCopy_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunOrderCopy_Height {
            get {
                return ((int)(this["RunOrderCopy_Height"]));
            }
            set {
                this["RunOrderCopy_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RunOrderCopy_Location {
            get {
                return ((global::System.Drawing.Point)(this["RunOrderCopy_Location"]));
            }
            set {
                this["RunOrderCopy_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunOrderElimNumSkiers {
            get {
                return ((int)(this["RunOrderElimNumSkiers"]));
            }
            set {
                this["RunOrderElimNumSkiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TourRegList_Sort {
            get {
                return ((string)(this["TourRegList_Sort"]));
            }
            set {
                this["TourRegList_Sort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string OverallSummaryAwardsNum {
            get {
                return ((string)(this["OverallSummaryAwardsNum"]));
            }
            set {
                this["OverallSummaryAwardsNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourReportProps_Width {
            get {
                return ((int)(this["TourReportProps_Width"]));
            }
            set {
                this["TourReportProps_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TourReportProps_Height {
            get {
                return ((int)(this["TourReportProps_Height"]));
            }
            set {
                this["TourReportProps_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TourReportProps_Location {
            get {
                return ((global::System.Drawing.Point)(this["TourReportProps_Location"]));
            }
            set {
                this["TourReportProps_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TrickScoreSummary_Location {
            get {
                return ((global::System.Drawing.Point)(this["TrickScoreSummary_Location"]));
            }
            set {
                this["TrickScoreSummary_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditMemberOfficialRatings_Width {
            get {
                return ((int)(this["EditMemberOfficialRatings_Width"]));
            }
            set {
                this["EditMemberOfficialRatings_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditMemberOfficialRatings_Height {
            get {
                return ((int)(this["EditMemberOfficialRatings_Height"]));
            }
            set {
                this["EditMemberOfficialRatings_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditMemberOfficialRatings_Location {
            get {
                return ((global::System.Drawing.Point)(this["EditMemberOfficialRatings_Location"]));
            }
            set {
                this["EditMemberOfficialRatings_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataAccessTraceActive {
            get {
                return ((bool)(this["DataAccessTraceActive"]));
            }
            set {
                this["DataAccessTraceActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoadVideosFile_Width {
            get {
                return ((int)(this["LoadVideosFile_Width"]));
            }
            set {
                this["LoadVideosFile_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoadVideosFile_Height {
            get {
                return ((int)(this["LoadVideosFile_Height"]));
            }
            set {
                this["LoadVideosFile_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LoadVideosFile_Location {
            get {
                return ((global::System.Drawing.Point)(this["LoadVideosFile_Location"]));
            }
            set {
                this["LoadVideosFile_Location"] = value;
            }
        }
    }
}
